# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chord_id_test_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChordIDTestWindow(object):
    def setupUi(self, ChordIDTestWindow):
        ChordIDTestWindow.setObjectName("ChordIDTestWindow")
        ChordIDTestWindow.resize(1445, 582)
        self.centralwidget = QtWidgets.QWidget(ChordIDTestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 150, 651, 421))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.play_chord_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.play_chord_button.setFont(font)
        self.play_chord_button.setObjectName("play_chord_button")
        self.horizontalLayout_5.addWidget(self.play_chord_button)
        self.play_arpeggio_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.play_arpeggio_button.setFont(font)
        self.play_arpeggio_button.setObjectName("play_arpeggio_button")
        self.horizontalLayout_5.addWidget(self.play_arpeggio_button)
        self.skip_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.skip_button.setFont(font)
        self.skip_button.setObjectName("skip_button")
        self.horizontalLayout_5.addWidget(self.skip_button)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.chord_buttonGroup = QtWidgets.QButtonGroup(ChordIDTestWindow)
        self.chord_buttonGroup.setObjectName("chord_buttonGroup")
        self.chord_buttonGroup.addButton(self.pushButton)
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.chord_buttonGroup.addButton(self.pushButton_2)
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.chord_buttonGroup.addButton(self.pushButton_3)
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.chord_buttonGroup.addButton(self.pushButton_4)
        self.horizontalLayout.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.chord_buttonGroup.addButton(self.pushButton_5)
        self.horizontalLayout.addWidget(self.pushButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName("pushButton_6")
        self.chord_buttonGroup.addButton(self.pushButton_6)
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_7.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName("pushButton_7")
        self.chord_buttonGroup.addButton(self.pushButton_7)
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_8.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName("pushButton_8")
        self.chord_buttonGroup.addButton(self.pushButton_8)
        self.horizontalLayout_2.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_9.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.chord_buttonGroup.addButton(self.pushButton_9)
        self.horizontalLayout_2.addWidget(self.pushButton_9)
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_10.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.chord_buttonGroup.addButton(self.pushButton_10)
        self.horizontalLayout_2.addWidget(self.pushButton_10)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_11.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.chord_buttonGroup.addButton(self.pushButton_11)
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_12.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.chord_buttonGroup.addButton(self.pushButton_12)
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.pushButton_13 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_13.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setObjectName("pushButton_13")
        self.chord_buttonGroup.addButton(self.pushButton_13)
        self.horizontalLayout_4.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_14.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName("pushButton_14")
        self.chord_buttonGroup.addButton(self.pushButton_14)
        self.horizontalLayout_4.addWidget(self.pushButton_14)
        self.pushButton_15 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_15.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName("pushButton_15")
        self.chord_buttonGroup.addButton(self.pushButton_15)
        self.horizontalLayout_4.addWidget(self.pushButton_15)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(740, 120, 731, 381))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.select_all1 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_all1.setFont(font)
        self.select_all1.setObjectName("select_all1")
        self.verticalLayout_2.addWidget(self.select_all1)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.buttonGroup1 = QtWidgets.QButtonGroup(ChordIDTestWindow)
        self.buttonGroup1.setObjectName("buttonGroup1")
        self.buttonGroup1.setExclusive(False)
        self.buttonGroup1.addButton(self.checkBox)
        self.verticalLayout_2.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.buttonGroup1.addButton(self.checkBox_2)
        self.verticalLayout_2.addWidget(self.checkBox_2)
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.buttonGroup1.addButton(self.checkBox_3)
        self.verticalLayout_2.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setObjectName("checkBox_4")
        self.buttonGroup1.addButton(self.checkBox_4)
        self.verticalLayout_2.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_5.setFont(font)
        self.checkBox_5.setObjectName("checkBox_5")
        self.buttonGroup1.addButton(self.checkBox_5)
        self.verticalLayout_2.addWidget(self.checkBox_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.select_all2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_all2.setFont(font)
        self.select_all2.setObjectName("select_all2")
        self.verticalLayout_3.addWidget(self.select_all2)
        self.checkBox_6 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_6.setFont(font)
        self.checkBox_6.setObjectName("checkBox_6")
        self.buttonGroup2 = QtWidgets.QButtonGroup(ChordIDTestWindow)
        self.buttonGroup2.setObjectName("buttonGroup2")
        self.buttonGroup2.setExclusive(False)
        self.buttonGroup2.addButton(self.checkBox_6)
        self.verticalLayout_3.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_7.setFont(font)
        self.checkBox_7.setObjectName("checkBox_7")
        self.buttonGroup2.addButton(self.checkBox_7)
        self.verticalLayout_3.addWidget(self.checkBox_7)
        self.checkBox_8 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_8.setFont(font)
        self.checkBox_8.setObjectName("checkBox_8")
        self.buttonGroup2.addButton(self.checkBox_8)
        self.verticalLayout_3.addWidget(self.checkBox_8)
        self.checkBox_9 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_9.setFont(font)
        self.checkBox_9.setObjectName("checkBox_9")
        self.buttonGroup2.addButton(self.checkBox_9)
        self.verticalLayout_3.addWidget(self.checkBox_9)
        self.checkBox_10 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_10.setFont(font)
        self.checkBox_10.setObjectName("checkBox_10")
        self.buttonGroup2.addButton(self.checkBox_10)
        self.verticalLayout_3.addWidget(self.checkBox_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.select_all3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_all3.setFont(font)
        self.select_all3.setObjectName("select_all3")
        self.verticalLayout_4.addWidget(self.select_all3)
        self.checkBox_11 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_11.setFont(font)
        self.checkBox_11.setObjectName("checkBox_11")
        self.buttonGroup3 = QtWidgets.QButtonGroup(ChordIDTestWindow)
        self.buttonGroup3.setObjectName("buttonGroup3")
        self.buttonGroup3.setExclusive(False)
        self.buttonGroup3.addButton(self.checkBox_11)
        self.verticalLayout_4.addWidget(self.checkBox_11)
        self.checkBox_12 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_12.setFont(font)
        self.checkBox_12.setObjectName("checkBox_12")
        self.buttonGroup3.addButton(self.checkBox_12)
        self.verticalLayout_4.addWidget(self.checkBox_12)
        self.checkBox_13 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.buttonGroup3.addButton(self.checkBox_13)
        self.verticalLayout_4.addWidget(self.checkBox_13)
        self.checkBox_14 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.buttonGroup3.addButton(self.checkBox_14)
        self.verticalLayout_4.addWidget(self.checkBox_14)
        self.checkBox_15 = QtWidgets.QCheckBox(self.horizontalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.buttonGroup3.addButton(self.checkBox_15)
        self.verticalLayout_4.addWidget(self.checkBox_15)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 0, 711, 71))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(740, 10, 591, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(30, 100, 381, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output_label.setFont(font)
        self.output_label.setText("")
        self.output_label.setObjectName("output_label")
        self.score_label = QtWidgets.QLabel(self.centralwidget)
        self.score_label.setGeometry(QtCore.QRect(420, 100, 341, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.score_label.setFont(font)
        self.score_label.setText("")
        self.score_label.setObjectName("score_label")
        self.select_all = QtWidgets.QCheckBox(self.centralwidget)
        self.select_all.setGeometry(QtCore.QRect(740, 80, 241, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_all.setFont(font)
        self.select_all.setObjectName("select_all")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(1000, 520, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        ChordIDTestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChordIDTestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1445, 18))
        self.menubar.setObjectName("menubar")
        ChordIDTestWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChordIDTestWindow)
        self.statusbar.setObjectName("statusbar")
        ChordIDTestWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChordIDTestWindow)
        QtCore.QMetaObject.connectSlotsByName(ChordIDTestWindow)

    def retranslateUi(self, ChordIDTestWindow):
        _translate = QtCore.QCoreApplication.translate
        ChordIDTestWindow.setWindowTitle(_translate("ChordIDTestWindow", "MainWindow"))
        self.play_chord_button.setText(_translate("ChordIDTestWindow", "Play Chord"))
        self.play_arpeggio_button.setText(_translate("ChordIDTestWindow", "Play Individual Notes"))
        self.skip_button.setText(_translate("ChordIDTestWindow", "Skip Chord"))
        self.pushButton.setAccessibleName(_translate("ChordIDTestWindow", "MAJOR_CHORD"))
        self.pushButton.setText(_translate("ChordIDTestWindow", "Major"))
        self.pushButton_2.setAccessibleName(_translate("ChordIDTestWindow", "MINOR_CHORD"))
        self.pushButton_2.setText(_translate("ChordIDTestWindow", "Minor"))
        self.pushButton_3.setAccessibleName(_translate("ChordIDTestWindow", "POWER_CHORD"))
        self.pushButton_3.setText(_translate("ChordIDTestWindow", "Power"))
        self.pushButton_4.setAccessibleName(_translate("ChordIDTestWindow", "SUS4_CHORD"))
        self.pushButton_4.setText(_translate("ChordIDTestWindow", "Sus4"))
        self.pushButton_5.setAccessibleName(_translate("ChordIDTestWindow", "SUS2_CHORD"))
        self.pushButton_5.setText(_translate("ChordIDTestWindow", "Sus2"))
        self.pushButton_6.setAccessibleName(_translate("ChordIDTestWindow", "DOM_7_CHORD"))
        self.pushButton_6.setText(_translate("ChordIDTestWindow", "Dom 7"))
        self.pushButton_7.setAccessibleName(_translate("ChordIDTestWindow", "MAJOR_MAJ7_CHORD"))
        self.pushButton_7.setText(_translate("ChordIDTestWindow", "Major maj7"))
        self.pushButton_8.setAccessibleName(_translate("ChordIDTestWindow", "MINOR_7_CHORD"))
        self.pushButton_8.setText(_translate("ChordIDTestWindow", "Minor 7"))
        self.pushButton_9.setAccessibleName(_translate("ChordIDTestWindow", "MINOR_MAJ7_CHORD"))
        self.pushButton_9.setText(_translate("ChordIDTestWindow", "Minor maj7"))
        self.pushButton_10.setAccessibleName(_translate("ChordIDTestWindow", "DOM_7_SUS4_CHORD"))
        self.pushButton_10.setText(_translate("ChordIDTestWindow", "Dom 7 Sus4"))
        self.pushButton_11.setAccessibleName(_translate("ChordIDTestWindow", "DIM_CHORD"))
        self.pushButton_11.setText(_translate("ChordIDTestWindow", "Dim"))
        self.pushButton_12.setAccessibleName(_translate("ChordIDTestWindow", "DIM7_CHORD"))
        self.pushButton_12.setText(_translate("ChordIDTestWindow", "Dim7"))
        self.pushButton_13.setAccessibleName(_translate("ChordIDTestWindow", "AUG_CHORD"))
        self.pushButton_13.setText(_translate("ChordIDTestWindow", "Aug"))
        self.pushButton_14.setAccessibleName(_translate("ChordIDTestWindow", "MAJOR_6_CHORD"))
        self.pushButton_14.setText(_translate("ChordIDTestWindow", "Major 6"))
        self.pushButton_15.setAccessibleName(_translate("ChordIDTestWindow", "MINOR_6_CHORD"))
        self.pushButton_15.setText(_translate("ChordIDTestWindow", "Minor 6"))
        self.select_all1.setText(_translate("ChordIDTestWindow", "Select all below:"))
        self.checkBox.setAccessibleName(_translate("ChordIDTestWindow", "MAJOR_CHORD"))
        self.checkBox.setText(_translate("ChordIDTestWindow", "Major Chord"))
        self.checkBox_2.setAccessibleName(_translate("ChordIDTestWindow", "MINOR_CHORD"))
        self.checkBox_2.setText(_translate("ChordIDTestWindow", "Minor Chord"))
        self.checkBox_3.setAccessibleName(_translate("ChordIDTestWindow", "POWER_CHORD"))
        self.checkBox_3.setText(_translate("ChordIDTestWindow", "Power Chord"))
        self.checkBox_4.setAccessibleName(_translate("ChordIDTestWindow", "SUS4_CHORD"))
        self.checkBox_4.setText(_translate("ChordIDTestWindow", "Suspended 4th Chord"))
        self.checkBox_5.setAccessibleName(_translate("ChordIDTestWindow", "SUS2_CHORD"))
        self.checkBox_5.setText(_translate("ChordIDTestWindow", "Suspended 2nd Chord"))
        self.select_all2.setText(_translate("ChordIDTestWindow", "Select all below:"))
        self.checkBox_6.setAccessibleName(_translate("ChordIDTestWindow", "DOM_7_CHORD"))
        self.checkBox_6.setText(_translate("ChordIDTestWindow", "Dominant 7 Chord"))
        self.checkBox_7.setAccessibleName(_translate("ChordIDTestWindow", "MAJOR_MAJ7_CHORD"))
        self.checkBox_7.setText(_translate("ChordIDTestWindow", "Major maj7 Chord"))
        self.checkBox_8.setAccessibleName(_translate("ChordIDTestWindow", "MINOR_7_CHORD"))
        self.checkBox_8.setText(_translate("ChordIDTestWindow", "Minor 7 Chord"))
        self.checkBox_9.setAccessibleName(_translate("ChordIDTestWindow", "MINOR_MAJ7_CHORD"))
        self.checkBox_9.setText(_translate("ChordIDTestWindow", "Minor maj7 Chord"))
        self.checkBox_10.setAccessibleName(_translate("ChordIDTestWindow", "DOM_7_SUS4_CHORD"))
        self.checkBox_10.setText(_translate("ChordIDTestWindow", "Dominant 7 Suspended 4 Chord"))
        self.select_all3.setText(_translate("ChordIDTestWindow", "Select all below:"))
        self.checkBox_11.setAccessibleName(_translate("ChordIDTestWindow", "DIM_CHORD"))
        self.checkBox_11.setText(_translate("ChordIDTestWindow", "Diminished Chord"))
        self.checkBox_12.setAccessibleName(_translate("ChordIDTestWindow", "DIM7_CHORD"))
        self.checkBox_12.setText(_translate("ChordIDTestWindow", "Diminished 7 Chord"))
        self.checkBox_13.setAccessibleName(_translate("ChordIDTestWindow", "AUG_CHORD"))
        self.checkBox_13.setText(_translate("ChordIDTestWindow", "Augmented Chord"))
        self.checkBox_14.setAccessibleName(_translate("ChordIDTestWindow", "MAJOR_6_CHORD"))
        self.checkBox_14.setText(_translate("ChordIDTestWindow", "Major 6 Chord"))
        self.checkBox_15.setAccessibleName(_translate("ChordIDTestWindow", "MINOR_6_CHORD"))
        self.checkBox_15.setText(_translate("ChordIDTestWindow", "Minor 6 Chord"))
        self.label.setText(_translate("ChordIDTestWindow", "Select a button below to hear the chord or notes"))
        self.label_2.setText(_translate("ChordIDTestWindow", "Select the chords you would like to be tested on"))
        self.select_all.setText(_translate("ChordIDTestWindow", "Select all chords"))
        self.close_button.setText(_translate("ChordIDTestWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChordIDTestWindow = QtWidgets.QMainWindow()
    ui = Ui_ChordIDTestWindow()
    ui.setupUi(ChordIDTestWindow)
    ChordIDTestWindow.show()
    sys.exit(app.exec_())
