# SCALES
MAJOR_SCALE = [0,2,4,5,7,9,11,12]
NATURAL_MINOR_SCALE = [0,2,3,5,7,8,10,12]
HARMONIC_MINOR_SCALE = [0,2,3,5,7,8,11,12]
MELODIC_MINOR_SCALE = [0,2,3,5,7,9,11,12,10,8,7,5,3,2,0]
PENTATONIC_SCALE = [0,2,4,7,9,12,9,7,4,2,0]
BLUES_SCALE = [0,3,5,6,7,10,12,10,7,6,5,3,0]

SCALES_DICT = {'MAJOR_SCALE':MAJOR_SCALE, 'NATURAL_MINOR_SCALE':NATURAL_MINOR_SCALE, 'HARMONIC_MINOR_SCALE':HARMONIC_MINOR_SCALE, 'MELODIC_MINOR_SCALE':MELODIC_MINOR_SCALE, 'PENTATONIC_SCALE':PENTATONIC_SCALE, 'BLUES_SCALE':BLUES_SCALE}

MAJOR_SCALES_DICT = {'C': ['C', 'D', 'E', 'F', 'G', 'A', 'B'],
                     'C#': ['C#', 'D#', 'E#', 'F#', 'G#', 'A#', 'B#'],
                     'Db': ['Db', 'Eb', 'F', 'Gb', 'Ab', 'Bb', 'C'],
                     'D': ['D', 'E', 'F#', 'G', 'A', 'B', 'C#'],
                     'Eb': ['Eb', 'F', 'G', 'Ab', 'Bb', 'C', 'D'],
                     'E': ['E', 'F#', 'G#', 'A', 'B', 'C#', 'D#'],
                     'F': ['F', 'G', 'A', 'Bb', 'C', 'D', 'E'],
                     'F#': ['F#', 'G#', 'A#', 'B', 'C#', 'D#', 'E#'],
                     'Gb': ['Gb', 'Ab', 'Bb', 'Cb', 'Db', 'Eb', 'F'],
                     'G': ['G', 'A', 'B', 'C', 'D', 'E', 'F#'],
                     'Ab': ['Ab', 'Bb', 'C', 'Db', 'Eb', 'F', 'G'],
                     'A': ['A', 'B', 'C#', 'D', 'E', 'F#', 'G#'],
                     'Bb': ['Bb', 'C', 'D', 'Eb', 'F', 'G', 'A'],
                     'B': ['B', 'C#', 'D#', 'E', 'F#', 'G#', 'A#']}

# INTERVALS
MINOR_2ND = 1
MAJOR_2ND = 2
MINOR_3RD = 3
MAJOR_3RD = 4
PERFECT_4TH = 5
TRITONE = 6
PERFECT_5TH = 7
MINOR_6TH = 8
MAJOR_6TH = 9
MINOR_7TH = 10
MAJOR_7TH = 11
OCTAVE = 12
MINOR_9TH = 13
MAJOR_9TH = 14
MINOR_10TH = 15
MAJOR_10TH = 16
PERFECT_11TH = 17
AUG_11TH = 18
PERFECT_12TH = 19
MINOR_13TH = 20
MAJOR_13TH = 21
MINOR_14TH = 22
MAJOR_14TH = 23
DOUBLE_OCTAVE = 24

# INTERVALS LIST
INTERVALS_LIST = ['MINOR_2ND', 'MAJOR_2ND', 'MINOR_3RD', 'MAJOR_3RD', 'PERFECT_4TH', 'TRITONE', 'PERFECT_5TH', 'MINOR_6TH', 'MAJOR_6TH', 'MINOR_7TH', 'MAJOR_7TH', 'OCTAVE',
                  'MINOR_9TH', 'MAJOR_9TH', 'MINOR_10TH', 'MAJOR_10TH', 'PERFECT_11TH', 'AUG_11TH', 'PERFECT_12TH', 'MINOR_13TH', 'MAJOR_13TH', 'MINOR_14TH', 'MAJOR_14TH', 'DOUBLE_OCTAVE']
INTERVALS_OCTAVE = INTERVALS_LIST[:12]

EASY_INTERVALS = ['MAJOR_3RD', 'PERFECT_5TH', 'OCTAVE']
MEDIUM_INTERVALS = EASY_INTERVALS + ['MINOR_2ND', 'MAJOR_2ND', 'MINOR_3RD', 'PERFECT_4TH']
HARD_INTERVALS = MEDIUM_INTERVALS + ['TRITONE', 'MINOR_6TH', 'MAJOR_6TH', 'MINOR_7TH', 'MAJOR_7TH']
INSANE_INTERVALS = HARD_INTERVALS + ['MINOR_9TH', 'MAJOR_9TH', 'PERFECT_11TH', 'AUG_11TH', 'MAJOR_13TH']

EASY_INTERVAL_CHORDS = ['MAJOR_2ND', 'PERFECT_4TH', 'PERFECT_5TH', 'MAJOR_6TH']
MAJOR_SCALE_INTERVALS = ['MAJOR_2ND', 'MAJOR_3RD', 'PERFECT_4TH', 'PERFECT_5TH', 'MAJOR_6TH', 'MAJOR_7TH']

# INTERVALS DICT
INTERVALS_DICT = {'MINOR_2ND':MINOR_2ND, 'MAJOR_2ND':MAJOR_2ND, 'MINOR_3RD':MINOR_3RD, 'MAJOR_3RD':MAJOR_3RD,
                  'PERFECT_4TH':PERFECT_4TH, 'TRITONE':TRITONE, 'PERFECT_5TH':PERFECT_5TH, 'OCTAVE':OCTAVE,
                  'MINOR_6TH':MINOR_6TH, 'MAJOR_6TH':MAJOR_6TH, 'MINOR_7TH':MINOR_7TH, 'MAJOR_7TH':MAJOR_7TH,
                  'MINOR_9TH':MINOR_9TH, 'MAJOR_9TH':MAJOR_9TH, 'MINOR_10TH':MINOR_10TH, 'MAJOR_10TH':MAJOR_10TH, 'PERFECT_11TH':PERFECT_11TH, 'AUG_11TH':AUG_11TH, 'PERFECT_12TH':PERFECT_12TH, 'MINOR_13TH':MINOR_13TH, 'MAJOR_13TH':MAJOR_13TH, 'MINOR_14TH':MINOR_14TH, 'MAJOR_14TH':MAJOR_14TH, 'DOUBLE_OCTAVE':DOUBLE_OCTAVE}

# CHORDS
MAJOR_CHORD = [0, MAJOR_3RD, PERFECT_5TH]
POWER_CHORD = [0, PERFECT_5TH]
MINOR_CHORD = [0, MINOR_3RD, PERFECT_5TH]

SUS4_CHORD = [0, PERFECT_4TH, PERFECT_5TH]
SUS2_CHORD = [0, MAJOR_2ND, PERFECT_5TH]

DOM_7_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MINOR_7TH]
MINOR_7_CHORD = [0, MINOR_3RD, PERFECT_5TH, MINOR_7TH]

MAJOR_MAJ7_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MAJOR_7TH]
MINOR_MAJ7_CHORD = [0, MINOR_3RD, PERFECT_5TH, MAJOR_7TH]

DOM_7_SUS4_CHORD = [0, PERFECT_4TH, PERFECT_5TH, MINOR_7TH]
MINOR_7_FLAT5_CHORD = [0, MINOR_3RD, TRITONE, MINOR_7TH]

DIM_CHORD = [0, MINOR_3RD, TRITONE]
DIM7_CHORD = [0, MINOR_3RD, TRITONE, MAJOR_6TH]

AUG_CHORD = [0, MAJOR_3RD, MINOR_6TH]

MAJOR_6_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MAJOR_6TH]
MINOR_6_CHORD = [0, MINOR_3RD, PERFECT_5TH, MAJOR_6TH]

MAJOR_ADD9_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MAJOR_9TH]
MINOR_ADD9_CHORD = [0, MINOR_3RD, PERFECT_5TH, MAJOR_9TH]

MINOR_9_CHORD = [0, MINOR_3RD, PERFECT_5TH, MINOR_7TH, MAJOR_9TH]
MAJOR_9_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MINOR_7TH, MAJOR_9TH]

MAJOR_69_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MAJOR_6TH, MAJOR_9TH]
MINOR_69_CHORD = [0, MINOR_3RD, PERFECT_5TH, MAJOR_6TH, MAJOR_9TH]

MINOR_FLAT6_CHORD = [0, MINOR_3RD, PERFECT_5TH, MINOR_6TH]
MAJOR_MAJ9_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MAJOR_7TH, MAJOR_9TH]
MAJOR_9_SUS4_CHORD = [0, PERFECT_4TH, PERFECT_5TH, MINOR_7TH, MAJOR_9TH]

MAJOR_11_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MINOR_7TH, MAJOR_9TH, PERFECT_11TH]
MINOR_11_CHORD = [0, MINOR_3RD, PERFECT_5TH, MINOR_7TH, MAJOR_9TH, PERFECT_11TH]
MAJOR_MAJ7_SHARP11_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MAJOR_7TH, AUG_11TH]

MAJOR_13_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MINOR_7TH, MAJOR_9TH, MAJOR_13TH]
MINOR_13_CHORD = [0, MINOR_3RD, PERFECT_5TH, MINOR_7TH, MAJOR_9TH, PERFECT_11TH, MAJOR_13TH]
MAJOR_MAJ13_CHORD = [0, MAJOR_3RD, PERFECT_5TH, MAJOR_7TH, MAJOR_9TH, MAJOR_13TH]
MAJOR_13_SUS4_CHORD = [0, PERFECT_4TH, PERFECT_5TH, MINOR_7TH, MAJOR_9TH, MAJOR_13TH]

# CHORDS LISTS
CHORDS_BASIC = ['MAJOR_CHORD', 'POWER_CHORD', 'MINOR_CHORD', 'SUS4_CHORD', 'SUS2_CHORD']
CHORDS_7 = ['DOM_7_CHORD', 'MINOR_7_CHORD', 'MAJOR_MAJ7_CHORD', 'MINOR_MAJ7_CHORD', 'DOM_7_SUS4_CHORD', 'MINOR_7_FLAT5_CHORD']
CHORDS_5 = ['DIM_CHORD', 'DIM7_CHORD', 'AUG_CHORD', 'MINOR_FLAT6_CHORD']
CHORDS_69 = ['MAJOR_6_CHORD', 'MINOR_6_CHORD', 'MAJOR_9_CHORD', 'MINOR_9_CHORD', 'MAJOR_ADD9_CHORD', 'MINOR_ADD9_CHORD', 'MAJOR_69_CHORD', 'MINOR_69_CHORD', 'MAJOR_MAJ9_CHORD', 'MAJOR_9_SUS4_CHORD']
CHORDS_1113 = ['MAJOR_11_CHORD', 'MINOR_11_CHORD', 'MAJOR_MAJ7_SHARP11_CHORD', 'MAJOR_13_CHORD', 'MINOR_13_CHORD', 'MAJOR_MAJ13_CHORD', 'MAJOR_13_SUS4_CHORD']

EASY_CHORDS_LIST = CHORDS_BASIC + CHORDS_7[:3] + CHORDS_5[:-2]
CHORDS_LIST = CHORDS_BASIC + CHORDS_7 + CHORDS_5 + CHORDS_69 + CHORDS_1113

# CHORDS DICTS
CHORDS_DICT = {'MAJOR_CHORD': MAJOR_CHORD, 'MINOR_CHORD': MINOR_CHORD, 'POWER_CHORD': POWER_CHORD, 'SUS4_CHORD':SUS4_CHORD, 'SUS2_CHORD':SUS2_CHORD,
                'DOM_7_CHORD':DOM_7_CHORD, 'MINOR_7_CHORD': MINOR_7_CHORD, 'MAJOR_MAJ7_CHORD':MAJOR_MAJ7_CHORD, 'MINOR_MAJ7_CHORD':MINOR_MAJ7_CHORD, 'DOM_7_SUS4_CHORD':DOM_7_SUS4_CHORD, 'MINOR_7_FLAT5_CHORD':MINOR_7_FLAT5_CHORD,
                'DIM_CHORD':DIM_CHORD, 'DIM7_CHORD':DIM7_CHORD, 'AUG_CHORD':AUG_CHORD,
                'MAJOR_6_CHORD':MAJOR_6_CHORD, 'MINOR_6_CHORD':MINOR_6_CHORD, 'MAJOR_9_CHORD':MAJOR_9_CHORD, 'MINOR_9_CHORD':MINOR_9_CHORD, 'MAJOR_ADD9_CHORD':MAJOR_ADD9_CHORD, 'MINOR_ADD9_CHORD':MINOR_ADD9_CHORD, 'MAJOR_69_CHORD':MAJOR_69_CHORD, 'MINOR_69_CHORD':MINOR_69_CHORD, 'MINOR_FLAT6_CHORD':MINOR_FLAT6_CHORD, 'MAJOR_MAJ9_CHORD':MAJOR_MAJ9_CHORD, 'MAJOR_9_SUS4_CHORD':MAJOR_9_SUS4_CHORD,
                'MAJOR_11_CHORD':MAJOR_11_CHORD, 'MINOR_11_CHORD':MINOR_11_CHORD, 'MAJOR_MAJ7_SHARP11_CHORD':MAJOR_MAJ7_SHARP11_CHORD, 'MAJOR_13_CHORD':MAJOR_13_CHORD, 'MINOR_13_CHORD':MINOR_13_CHORD, 'MAJOR_MAJ13_CHORD':MAJOR_MAJ13_CHORD, 'MAJOR_13_SUS4_CHORD':MAJOR_13_SUS4_CHORD}

CHORD_RELATIONS = {'MAJOR_2ND':['MINOR_CHORD','MAJOR_CHORD'], 'MAJOR_3RD':['MINOR_CHORD','MAJOR_CHORD'], 'PERFECT_4TH':['MAJOR_CHORD'], 'PERFECT_5TH':['MAJOR_CHORD'], 'MAJOR_6TH':['MINOR_CHORD'], 'MAJOR_7TH':['DIM_CHORD']}


# NOTES
C2 = 36
Db2 = 37
D2 = 38
Eb2 = 39
E2 = 40
F2 = 41
Gb2 = 42
G2 = 43
Ab2 = 44
A2 = 45
Bb2 = 46
B2 = 47
C3 = 48
Db3 = 49
D3 = 50
Eb3 = 51
E3 = 52
F3 = 53
Gb3 = 54
G3 = 55
Ab3 = 56
A3 = 57
Bb3 = 58
B3 = 59
C4 = 60
Db4 = 61
D4 = 62
Eb4 = 63
E4 = 64
F4 = 65
Gb4 = 66
G4 = 67
Ab4 = 68
A4 = 69
Bb4 = 70
B4 = 71
C5 = 72
Db5 = 73
D5 = 74
Eb5 = 75
E5 = 76
F5 = 77
Gb5 = 78
G5 = 79
Ab5 = 80
A5 = 81
Bb5 = 82
B5 = 83
C6 = 84

# NOTES SHORT-HANDS
MIDDLE_C = C4
C = C3
Db = Db3
D = D3
Eb = Eb3
E = E3
F = F3
Gb = Gb3
G = G3
Ab = Ab3
A = A3
Bb = Bb3
B = B3

# NOTES LIST
NOTES = [C2, Db2, D2, Eb2, E2, F2, Gb2, G2, Ab2, A2, Bb2, B2,
         C3, Db3, D3, Eb3, E3, F3, Gb3, G3, Ab3, A3, Bb3, B3,
         C4, Db4, D4, Eb4, E4, F4, Gb4, G4, Ab4, A4, Bb4, B4,
         C5, Db5, D5, Eb5, E5, F5, Gb5, G5, Ab5, A5, Bb5, B5, C6]
BASIC_NOTES = NOTES[13:26]

NOTES_DICT = {'C2':C2, 'Db2':Db2, 'D2':D2, 'Eb2':Eb2, 'E2':E2, 'F2':F2, 'Gb2':Gb2, 'G2':G2, 'Ab2':Ab2, 'A2':A2, 'Bb2':Bb2, 'B2':B2,
               'C3':C3, 'Db3':Db3, 'D3':D3, 'Eb3':Eb3, 'E3':E3, 'F3':F3, 'Gb3':Gb3, 'G3':G3, 'Ab3':Ab3, 'A3':A3, 'Bb3':Bb3, 'B3':B3,
               'C4':C4, 'Db4':Db4, 'D4':D4, 'Eb4':Eb4, 'E4':E4, 'F4':F4, 'Gb4':Gb4, 'G4':G4, 'Ab4':Ab4, 'A4':A4, 'Bb4':Bb4, 'B4':B4,
               'C5':C5, 'Db5':Db5, 'D5':D5, 'Eb5':Eb5, 'E5':E5, 'F5':F5, 'Gb5':Gb5, 'G5':G5, 'Ab5':Ab5, 'A5':A5, 'Bb5':Bb5, 'B5':B5, 'C6':C6}

# Link to all MIDI Codes
# http://www.ccarh.org/courses/253/handout/gminstruments/

# INSTRUMENT CODES
ACOUSTIC_GRAND_PIANO = 0
CHURCH_ORGAN = 19
ACOUSTIC_STEEL_GUITAR = 25
ACOUSTIC_BASS = 32
STRING_ENSEMBLE_1 = 48
SYNTH_STRINGS_1 = 50
CHOIR_AAH = 52
TRUMPET = 56
BRASS_SECTION = 61
ALTO_SAX = 65
TENOR_SAX = 66
FLUTE = 73
SQUARE_WAVE = 80
SAWTOOTH_WAVE = 81

# INSTRUMENTS SHORT-HANDS
PIANO = ACOUSTIC_GRAND_PIANO
ORGAN = CHURCH_ORGAN
GUITAR = ACOUSTIC_STEEL_GUITAR
BASS = ACOUSTIC_BASS
STRINGS = STRING_ENSEMBLE_1
SYNTH = SYNTH_STRINGS_1
CHOIR = CHOIR_AAH
BRASS = BRASS_SECTION
ALTO = ALTO_SAX
TENOR = TENOR_SAX
SQUARE = SQUARE_WAVE
SAWTOOTH = SAWTOOTH_WAVE

SOME_INSTRUMENTS = [PIANO, ORGAN, GUITAR, BASS, STRINGS, SYNTH, CHOIR, BRASS, TRUMPET, FLUTE, ALTO, TENOR, SQUARE, SAWTOOTH]