# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chord_relation_test_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChordRelationTestWindow(object):
    def setupUi(self, ChordRelationTestWindow):
        ChordRelationTestWindow.setObjectName("ChordRelationTestWindow")
        ChordRelationTestWindow.setEnabled(True)
        ChordRelationTestWindow.resize(1268, 568)
        self.centralwidget = QtWidgets.QWidget(ChordRelationTestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(800, 30, 591, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 0, 821, 151))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(10, 120, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output_label.setFont(font)
        self.output_label.setText("")
        self.output_label.setObjectName("output_label")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(900, 470, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        self.score_label = QtWidgets.QLabel(self.centralwidget)
        self.score_label.setGeometry(QtCore.QRect(600, 110, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.score_label.setFont(font)
        self.score_label.setText("")
        self.score_label.setObjectName("score_label")
        self.select_all = QtWidgets.QCheckBox(self.centralwidget)
        self.select_all.setGeometry(QtCore.QRect(800, 100, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_all.setFont(font)
        self.select_all.setObjectName("select_all")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 721, 291))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.replay_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.replay_button.setFont(font)
        self.replay_button.setObjectName("replay_button")
        self.horizontalLayout_4.addWidget(self.replay_button)
        self.skip_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.skip_button.setFont(font)
        self.skip_button.setObjectName("skip_button")
        self.horizontalLayout_4.addWidget(self.skip_button)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.IV_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.IV_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.IV_button.setFont(font)
        self.IV_button.setObjectName("IV_button")
        self.relation_buttonGroup = QtWidgets.QButtonGroup(ChordRelationTestWindow)
        self.relation_buttonGroup.setObjectName("relation_buttonGroup")
        self.relation_buttonGroup.addButton(self.IV_button)
        self.gridLayout_2.addWidget(self.IV_button, 2, 4, 1, 1)
        self.iii_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.iii_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.iii_button.setFont(font)
        self.iii_button.setObjectName("iii_button")
        self.relation_buttonGroup.addButton(self.iii_button)
        self.gridLayout_2.addWidget(self.iii_button, 1, 4, 1, 1)
        self.II_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.II_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.II_button.setFont(font)
        self.II_button.setObjectName("II_button")
        self.relation_buttonGroup.addButton(self.II_button)
        self.gridLayout_2.addWidget(self.II_button, 1, 3, 1, 1)
        self.vii_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.vii_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vii_button.setFont(font)
        self.vii_button.setObjectName("vii_button")
        self.relation_buttonGroup.addButton(self.vii_button)
        self.gridLayout_2.addWidget(self.vii_button, 3, 4, 1, 1)
        self.vi_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.vi_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.vi_button.setFont(font)
        self.vi_button.setObjectName("vi_button")
        self.relation_buttonGroup.addButton(self.vi_button)
        self.gridLayout_2.addWidget(self.vi_button, 3, 3, 1, 1)
        self.iv_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.iv_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.iv_button.setFont(font)
        self.iv_button.setObjectName("iv_button")
        self.relation_buttonGroup.addButton(self.iv_button)
        self.gridLayout_2.addWidget(self.iv_button, 2, 3, 1, 1)
        self.III_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.III_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.III_button.setFont(font)
        self.III_button.setObjectName("III_button")
        self.relation_buttonGroup.addButton(self.III_button)
        self.gridLayout_2.addWidget(self.III_button, 2, 2, 1, 1)
        self.V_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.V_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.V_button.setFont(font)
        self.V_button.setObjectName("V_button")
        self.relation_buttonGroup.addButton(self.V_button)
        self.gridLayout_2.addWidget(self.V_button, 3, 2, 1, 1)
        self.ii_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ii_button.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ii_button.setFont(font)
        self.ii_button.setObjectName("ii_button")
        self.relation_buttonGroup.addButton(self.ii_button)
        self.gridLayout_2.addWidget(self.ii_button, 1, 2, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_2)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(780, 170, 441, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.checkBox_14 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_14.setFont(font)
        self.checkBox_14.setObjectName("checkBox_14")
        self.select_buttonGroup = QtWidgets.QButtonGroup(ChordRelationTestWindow)
        self.select_buttonGroup.setObjectName("select_buttonGroup")
        self.select_buttonGroup.setExclusive(False)
        self.select_buttonGroup.addButton(self.checkBox_14)
        self.gridLayout_3.addWidget(self.checkBox_14, 0, 1, 1, 1)
        self.checkBox_16 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_16.setFont(font)
        self.checkBox_16.setChecked(False)
        self.checkBox_16.setObjectName("checkBox_16")
        self.select_buttonGroup.addButton(self.checkBox_16)
        self.gridLayout_3.addWidget(self.checkBox_16, 1, 0, 1, 1)
        self.checkBox_15 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_15.setFont(font)
        self.checkBox_15.setObjectName("checkBox_15")
        self.select_buttonGroup.addButton(self.checkBox_15)
        self.gridLayout_3.addWidget(self.checkBox_15, 0, 2, 1, 1)
        self.checkBox_13 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_13.setFont(font)
        self.checkBox_13.setObjectName("checkBox_13")
        self.select_buttonGroup.addButton(self.checkBox_13)
        self.gridLayout_3.addWidget(self.checkBox_13, 0, 0, 1, 1)
        self.checkBox_17 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_17.setFont(font)
        self.checkBox_17.setChecked(True)
        self.checkBox_17.setObjectName("checkBox_17")
        self.select_buttonGroup.addButton(self.checkBox_17)
        self.gridLayout_3.addWidget(self.checkBox_17, 1, 2, 1, 1)
        self.checkBox_18 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_18.setFont(font)
        self.checkBox_18.setObjectName("checkBox_18")
        self.select_buttonGroup.addButton(self.checkBox_18)
        self.gridLayout_3.addWidget(self.checkBox_18, 1, 1, 1, 1)
        self.checkBox_19 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_19.setFont(font)
        self.checkBox_19.setChecked(True)
        self.checkBox_19.setObjectName("checkBox_19")
        self.select_buttonGroup.addButton(self.checkBox_19)
        self.gridLayout_3.addWidget(self.checkBox_19, 2, 0, 1, 1)
        self.checkBox_20 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_20.setFont(font)
        self.checkBox_20.setChecked(True)
        self.checkBox_20.setObjectName("checkBox_20")
        self.select_buttonGroup.addButton(self.checkBox_20)
        self.gridLayout_3.addWidget(self.checkBox_20, 2, 1, 1, 1)
        self.checkBox_23 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_23.setFont(font)
        self.checkBox_23.setObjectName("checkBox_23")
        self.select_buttonGroup.addButton(self.checkBox_23)
        self.gridLayout_3.addWidget(self.checkBox_23, 2, 2, 1, 1)
        ChordRelationTestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChordRelationTestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1268, 18))
        self.menubar.setObjectName("menubar")
        ChordRelationTestWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChordRelationTestWindow)
        self.statusbar.setObjectName("statusbar")
        ChordRelationTestWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChordRelationTestWindow)
        QtCore.QMetaObject.connectSlotsByName(ChordRelationTestWindow)

    def retranslateUi(self, ChordRelationTestWindow):
        _translate = QtCore.QCoreApplication.translate
        ChordRelationTestWindow.setWindowTitle(_translate("ChordRelationTestWindow", "ChordRelationTestWindow"))
        self.label_2.setText(_translate("ChordRelationTestWindow", "Select the relationships you would like to test"))
        self.label.setText(_translate("ChordRelationTestWindow", "Select the relationship you just heard"))
        self.close_button.setText(_translate("ChordRelationTestWindow", "Close"))
        self.select_all.setText(_translate("ChordRelationTestWindow", "Select all"))
        self.replay_button.setText(_translate("ChordRelationTestWindow", "Replay Chords"))
        self.skip_button.setText(_translate("ChordRelationTestWindow", "Skip this relation"))
        self.IV_button.setAccessibleName(_translate("ChordRelationTestWindow", "PERFECT_4TH MAJOR_CHORD"))
        self.IV_button.setText(_translate("ChordRelationTestWindow", "IV"))
        self.iii_button.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_3RD MINOR_CHORD"))
        self.iii_button.setText(_translate("ChordRelationTestWindow", "iii"))
        self.II_button.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_2ND MAJOR_CHORD"))
        self.II_button.setText(_translate("ChordRelationTestWindow", "II"))
        self.vii_button.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_7TH DIM_CHORD"))
        self.vii_button.setText(_translate("ChordRelationTestWindow", "vii dim"))
        self.vi_button.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_6TH MINOR_CHORD"))
        self.vi_button.setText(_translate("ChordRelationTestWindow", "vi"))
        self.iv_button.setAccessibleName(_translate("ChordRelationTestWindow", "PERFECT_4TH MINOR_CHORD"))
        self.iv_button.setText(_translate("ChordRelationTestWindow", "iv"))
        self.III_button.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_3RD MAJOR_CHORD"))
        self.III_button.setText(_translate("ChordRelationTestWindow", "III"))
        self.V_button.setAccessibleName(_translate("ChordRelationTestWindow", "PERFECT_5TH MAJOR_CHORD"))
        self.V_button.setText(_translate("ChordRelationTestWindow", "V"))
        self.ii_button.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_2ND MINOR_CHORD"))
        self.ii_button.setText(_translate("ChordRelationTestWindow", "ii"))
        self.checkBox_14.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_2ND MAJOR_CHORD"))
        self.checkBox_14.setText(_translate("ChordRelationTestWindow", "II"))
        self.checkBox_16.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_3RD MAJOR_CHORD"))
        self.checkBox_16.setText(_translate("ChordRelationTestWindow", "III"))
        self.checkBox_15.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_3RD MINOR_CHORD"))
        self.checkBox_15.setText(_translate("ChordRelationTestWindow", "iii"))
        self.checkBox_13.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_2ND MINOR_CHORD"))
        self.checkBox_13.setText(_translate("ChordRelationTestWindow", "ii"))
        self.checkBox_17.setAccessibleName(_translate("ChordRelationTestWindow", "PERFECT_4TH MAJOR_CHORD"))
        self.checkBox_17.setText(_translate("ChordRelationTestWindow", "IV"))
        self.checkBox_18.setAccessibleName(_translate("ChordRelationTestWindow", "PERFECT_4TH MINOR_CHORD"))
        self.checkBox_18.setText(_translate("ChordRelationTestWindow", "iv"))
        self.checkBox_19.setAccessibleName(_translate("ChordRelationTestWindow", "PERFECT_5TH MAJOR_CHORD"))
        self.checkBox_19.setText(_translate("ChordRelationTestWindow", "V"))
        self.checkBox_20.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_6TH MINOR_CHORD"))
        self.checkBox_20.setText(_translate("ChordRelationTestWindow", "vi"))
        self.checkBox_23.setAccessibleName(_translate("ChordRelationTestWindow", "MAJOR_7TH DIM_CHORD"))
        self.checkBox_23.setText(_translate("ChordRelationTestWindow", "vii dim"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChordRelationTestWindow = QtWidgets.QMainWindow()
    ui = Ui_ChordRelationTestWindow()
    ui.setupUi(ChordRelationTestWindow)
    ChordRelationTestWindow.show()
    sys.exit(app.exec_())
