# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chord_degree_test_window_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ChordDegreeTestWindow(object):
    def setupUi(self, ChordDegreeTestWindow):
        ChordDegreeTestWindow.setObjectName("ChordDegreeTestWindow")
        ChordDegreeTestWindow.resize(1222, 561)
        self.centralwidget = QtWidgets.QWidget(ChordDegreeTestWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.close_button = QtWidgets.QPushButton(self.centralwidget)
        self.close_button.setGeometry(QtCore.QRect(900, 470, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.close_button.setFont(font)
        self.close_button.setObjectName("close_button")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setEnabled(True)
        self.label.setGeometry(QtCore.QRect(10, 0, 761, 171))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.output_label = QtWidgets.QLabel(self.centralwidget)
        self.output_label.setGeometry(QtCore.QRect(10, 120, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.output_label.setFont(font)
        self.output_label.setText("")
        self.output_label.setObjectName("output_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(780, 0, 431, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 761, 351))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.degree_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.degree_label.setFont(font)
        self.degree_label.setObjectName("degree_label")
        self.gridLayout.addWidget(self.degree_label, 2, 0, 1, 1)
        self.skip_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.skip_button.setFont(font)
        self.skip_button.setObjectName("skip_button")
        self.gridLayout.addWidget(self.skip_button, 0, 1, 1, 1)
        self.key_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.key_label.setFont(font)
        self.key_label.setObjectName("key_label")
        self.gridLayout.addWidget(self.key_label, 0, 0, 1, 1)
        self.enharmonic_switch = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.enharmonic_switch.setFont(font)
        self.enharmonic_switch.setObjectName("enharmonic_switch")
        self.gridLayout.addWidget(self.enharmonic_switch, 2, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.grid_all = QtWidgets.QGridLayout()
        self.grid_all.setObjectName("grid_all")
        self.G_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.G_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.G_button.setFont(font)
        self.G_button.setObjectName("G_button")
        self.chord_buttonGroup = QtWidgets.QButtonGroup(ChordDegreeTestWindow)
        self.chord_buttonGroup.setObjectName("chord_buttonGroup")
        self.chord_buttonGroup.addButton(self.G_button)
        self.grid_all.addWidget(self.G_button, 4, 1, 1, 1)
        self.Fs_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Fs_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Fs_button.setFont(font)
        self.Fs_button.setObjectName("Fs_button")
        self.chord_buttonGroup.addButton(self.Fs_button)
        self.grid_all.addWidget(self.Fs_button, 2, 4, 1, 1)
        self.Bs_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Bs_button.setFont(font)
        self.Bs_button.setObjectName("Bs_button")
        self.chord_buttonGroup.addButton(self.Bs_button)
        self.grid_all.addWidget(self.Bs_button, 5, 3, 1, 1)
        self.E_button_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.E_button_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.E_button_2.setFont(font)
        self.E_button_2.setObjectName("E_button_2")
        self.chord_buttonGroup.addButton(self.E_button_2)
        self.grid_all.addWidget(self.E_button_2, 2, 1, 1, 1)
        self.A_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.A_button.setFont(font)
        self.A_button.setObjectName("A_button")
        self.chord_buttonGroup.addButton(self.A_button)
        self.grid_all.addWidget(self.A_button, 4, 4, 1, 1)
        self.Gs_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Gs_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Gs_button.setFont(font)
        self.Gs_button.setObjectName("Gs_button")
        self.chord_buttonGroup.addButton(self.Gs_button)
        self.grid_all.addWidget(self.Gs_button, 4, 2, 1, 1)
        self.Cs_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Cs_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Cs_button.setFont(font)
        self.Cs_button.setObjectName("Cs_button")
        self.chord_buttonGroup.addButton(self.Cs_button)
        self.grid_all.addWidget(self.Cs_button, 1, 1, 1, 1)
        self.Gb_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Gb_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Gb_button.setFont(font)
        self.Gb_button.setObjectName("Gb_button")
        self.chord_buttonGroup.addButton(self.Gb_button)
        self.grid_all.addWidget(self.Gb_button, 4, 0, 1, 1)
        self.Ds_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Ds_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Ds_button.setFont(font)
        self.Ds_button.setObjectName("Ds_button")
        self.chord_buttonGroup.addButton(self.Ds_button)
        self.grid_all.addWidget(self.Ds_button, 1, 4, 1, 1)
        self.Eb_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Eb_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Eb_button.setFont(font)
        self.Eb_button.setObjectName("Eb_button")
        self.chord_buttonGroup.addButton(self.Eb_button)
        self.grid_all.addWidget(self.Eb_button, 2, 0, 1, 1)
        self.B_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.B_button.setFont(font)
        self.B_button.setObjectName("B_button")
        self.chord_buttonGroup.addButton(self.B_button)
        self.grid_all.addWidget(self.B_button, 5, 2, 1, 1)
        self.C_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.C_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.C_button.setFont(font)
        self.C_button.setObjectName("C_button")
        self.chord_buttonGroup.addButton(self.C_button)
        self.grid_all.addWidget(self.C_button, 1, 0, 1, 1)
        self.Bb_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Bb_button.setFont(font)
        self.Bb_button.setObjectName("Bb_button")
        self.chord_buttonGroup.addButton(self.Bb_button)
        self.grid_all.addWidget(self.Bb_button, 5, 1, 1, 1)
        self.Ab_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Ab_button.setFont(font)
        self.Ab_button.setObjectName("Ab_button")
        self.chord_buttonGroup.addButton(self.Ab_button)
        self.grid_all.addWidget(self.Ab_button, 4, 3, 1, 1)
        self.Db_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Db_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Db_button.setFont(font)
        self.Db_button.setObjectName("Db_button")
        self.chord_buttonGroup.addButton(self.Db_button)
        self.grid_all.addWidget(self.Db_button, 1, 2, 1, 1)
        self.F_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.F_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.F_button.setFont(font)
        self.F_button.setObjectName("F_button")
        self.chord_buttonGroup.addButton(self.F_button)
        self.grid_all.addWidget(self.F_button, 2, 3, 1, 1)
        self.Es_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Es_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.Es_button.setFont(font)
        self.Es_button.setObjectName("Es_button")
        self.chord_buttonGroup.addButton(self.Es_button)
        self.grid_all.addWidget(self.Es_button, 2, 2, 1, 1)
        self.As_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.As_button.setFont(font)
        self.As_button.setObjectName("As_button")
        self.chord_buttonGroup.addButton(self.As_button)
        self.grid_all.addWidget(self.As_button, 5, 0, 1, 1)
        self.D_button = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.D_button.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.D_button.setFont(font)
        self.D_button.setObjectName("D_button")
        self.chord_buttonGroup.addButton(self.D_button)
        self.grid_all.addWidget(self.D_button, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.grid_all)
        self.grid_enharmonics_3 = QtWidgets.QGridLayout()
        self.grid_enharmonics_3.setObjectName("grid_enharmonics_3")
        self.GsAb_button_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.GsAb_button_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.GsAb_button_3.setFont(font)
        self.GsAb_button_3.setObjectName("GsAb_button_3")
        self.chord_buttonGroup_enh = QtWidgets.QButtonGroup(ChordDegreeTestWindow)
        self.chord_buttonGroup_enh.setObjectName("chord_buttonGroup_enh")
        self.chord_buttonGroup_enh.addButton(self.GsAb_button_3)
        self.grid_enharmonics_3.addWidget(self.GsAb_button_3, 3, 0, 1, 1)
        self.B_button_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.B_button_5.setFont(font)
        self.B_button_5.setObjectName("B_button_5")
        self.chord_buttonGroup_enh.addButton(self.B_button_5)
        self.grid_enharmonics_3.addWidget(self.B_button_5, 3, 4, 1, 1)
        self.A_button_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.A_button_5.setFont(font)
        self.A_button_5.setObjectName("A_button_5")
        self.chord_buttonGroup_enh.addButton(self.A_button_5)
        self.grid_enharmonics_3.addWidget(self.A_button_5, 3, 2, 1, 1)
        self.AsBb_button_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.AsBb_button_3.setFont(font)
        self.AsBb_button_3.setObjectName("AsBb_button_3")
        self.chord_buttonGroup_enh.addButton(self.AsBb_button_3)
        self.grid_enharmonics_3.addWidget(self.AsBb_button_3, 3, 3, 1, 1)
        self.C_button_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.C_button_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.C_button_5.setFont(font)
        self.C_button_5.setObjectName("C_button_5")
        self.chord_buttonGroup_enh.addButton(self.C_button_5)
        self.grid_enharmonics_3.addWidget(self.C_button_5, 1, 0, 1, 1)
        self.CsDb_button_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.CsDb_button_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.CsDb_button_3.setFont(font)
        self.CsDb_button_3.setObjectName("CsDb_button_3")
        self.chord_buttonGroup_enh.addButton(self.CsDb_button_3)
        self.grid_enharmonics_3.addWidget(self.CsDb_button_3, 1, 2, 1, 1)
        self.DsEb_button_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.DsEb_button_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DsEb_button_3.setFont(font)
        self.DsEb_button_3.setObjectName("DsEb_button_3")
        self.chord_buttonGroup_enh.addButton(self.DsEb_button_3)
        self.grid_enharmonics_3.addWidget(self.DsEb_button_3, 1, 4, 1, 1)
        self.F_button_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.F_button_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.F_button_5.setFont(font)
        self.F_button_5.setObjectName("F_button_5")
        self.chord_buttonGroup_enh.addButton(self.F_button_5)
        self.grid_enharmonics_3.addWidget(self.F_button_5, 2, 2, 1, 1)
        self.FsGb_button_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.FsGb_button_3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.FsGb_button_3.setFont(font)
        self.FsGb_button_3.setObjectName("FsGb_button_3")
        self.chord_buttonGroup_enh.addButton(self.FsGb_button_3)
        self.grid_enharmonics_3.addWidget(self.FsGb_button_3, 2, 3, 1, 1)
        self.G_button_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.G_button_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.G_button_5.setFont(font)
        self.G_button_5.setObjectName("G_button_5")
        self.chord_buttonGroup_enh.addButton(self.G_button_5)
        self.grid_enharmonics_3.addWidget(self.G_button_5, 2, 4, 1, 1)
        self.D_button_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.D_button_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.D_button_5.setFont(font)
        self.D_button_5.setObjectName("D_button_5")
        self.chord_buttonGroup_enh.addButton(self.D_button_5)
        self.grid_enharmonics_3.addWidget(self.D_button_5, 1, 3, 1, 1)
        self.E_button_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.E_button_5.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.E_button_5.setFont(font)
        self.E_button_5.setObjectName("E_button_5")
        self.chord_buttonGroup_enh.addButton(self.E_button_5)
        self.grid_enharmonics_3.addWidget(self.E_button_5, 2, 0, 1, 1)
        self.verticalLayout.addLayout(self.grid_enharmonics_3)
        self.score_label = QtWidgets.QLabel(self.centralwidget)
        self.score_label.setGeometry(QtCore.QRect(600, 110, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.score_label.setFont(font)
        self.score_label.setText("")
        self.score_label.setObjectName("score_label")
        self.select_all_keys_button = QtWidgets.QCheckBox(self.centralwidget)
        self.select_all_keys_button.setGeometry(QtCore.QRect(800, 100, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_all_keys_button.setFont(font)
        self.select_all_keys_button.setObjectName("select_all_keys_button")
        self.select_all_degrees_button = QtWidgets.QCheckBox(self.centralwidget)
        self.select_all_degrees_button.setGeometry(QtCore.QRect(1020, 100, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_all_degrees_button.setFont(font)
        self.select_all_degrees_button.setObjectName("select_all_degrees_button")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(780, 140, 429, 319))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.select_Eb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_Eb.setFont(font)
        self.select_Eb.setChecked(False)
        self.select_Eb.setObjectName("select_Eb")
        self.keys_buttonGroup = QtWidgets.QButtonGroup(ChordDegreeTestWindow)
        self.keys_buttonGroup.setObjectName("keys_buttonGroup")
        self.keys_buttonGroup.setExclusive(False)
        self.keys_buttonGroup.addButton(self.select_Eb)
        self.gridLayout_2.addWidget(self.select_Eb, 5, 0, 1, 1)
        self.select_5 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_5.setFont(font)
        self.select_5.setChecked(True)
        self.select_5.setObjectName("select_5")
        self.degrees_buttonGroup = QtWidgets.QButtonGroup(ChordDegreeTestWindow)
        self.degrees_buttonGroup.setObjectName("degrees_buttonGroup")
        self.degrees_buttonGroup.setExclusive(False)
        self.degrees_buttonGroup.addButton(self.select_5)
        self.gridLayout_2.addWidget(self.select_5, 4, 2, 1, 1)
        self.select_Bb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_Bb.setFont(font)
        self.select_Bb.setObjectName("select_Bb")
        self.keys_buttonGroup.addButton(self.select_Bb)
        self.gridLayout_2.addWidget(self.select_Bb, 6, 1, 1, 1)
        self.select_Fs = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_Fs.setFont(font)
        self.select_Fs.setObjectName("select_Fs")
        self.keys_buttonGroup.addButton(self.select_Fs)
        self.gridLayout_2.addWidget(self.select_Fs, 0, 1, 1, 1)
        self.select_Db = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_Db.setFont(font)
        self.select_Db.setObjectName("select_Db")
        self.keys_buttonGroup.addButton(self.select_Db)
        self.gridLayout_2.addWidget(self.select_Db, 2, 0, 1, 1)
        self.select_F = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_F.setFont(font)
        self.select_F.setObjectName("select_F")
        self.keys_buttonGroup.addButton(self.select_F)
        self.gridLayout_2.addWidget(self.select_F, 7, 0, 1, 1)
        self.select_E = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.select_E.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_E.setFont(font)
        self.select_E.setChecked(False)
        self.select_E.setObjectName("select_E")
        self.keys_buttonGroup.addButton(self.select_E)
        self.gridLayout_2.addWidget(self.select_E, 6, 0, 1, 1)
        self.select_7 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_7.setFont(font)
        self.select_7.setChecked(False)
        self.select_7.setObjectName("select_7")
        self.degrees_buttonGroup.addButton(self.select_7)
        self.gridLayout_2.addWidget(self.select_7, 6, 2, 1, 1)
        self.select_A = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_A.setFont(font)
        self.select_A.setChecked(False)
        self.select_A.setObjectName("select_A")
        self.keys_buttonGroup.addButton(self.select_A)
        self.gridLayout_2.addWidget(self.select_A, 5, 1, 1, 1)
        self.select_G = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_G.setFont(font)
        self.select_G.setChecked(True)
        self.select_G.setObjectName("select_G")
        self.keys_buttonGroup.addButton(self.select_G)
        self.gridLayout_2.addWidget(self.select_G, 2, 1, 1, 1)
        self.select_6 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_6.setFont(font)
        self.select_6.setChecked(True)
        self.select_6.setObjectName("select_6")
        self.degrees_buttonGroup.addButton(self.select_6)
        self.gridLayout_2.addWidget(self.select_6, 5, 2, 1, 1)
        self.select_Gb = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_Gb.setFont(font)
        self.select_Gb.setObjectName("select_Gb")
        self.keys_buttonGroup.addButton(self.select_Gb)
        self.gridLayout_2.addWidget(self.select_Gb, 1, 1, 1, 1)
        self.select_C = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_C.setFont(font)
        self.select_C.setChecked(True)
        self.select_C.setObjectName("select_C")
        self.keys_buttonGroup.addButton(self.select_C)
        self.gridLayout_2.addWidget(self.select_C, 0, 0, 1, 1)
        self.select_Cs = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_Cs.setFont(font)
        self.select_Cs.setObjectName("select_Cs")
        self.keys_buttonGroup.addButton(self.select_Cs)
        self.gridLayout_2.addWidget(self.select_Cs, 1, 0, 1, 1)
        self.select_2 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_2.setFont(font)
        self.select_2.setChecked(False)
        self.select_2.setObjectName("select_2")
        self.degrees_buttonGroup.addButton(self.select_2)
        self.gridLayout_2.addWidget(self.select_2, 0, 2, 1, 1)
        self.select_3 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_3.setFont(font)
        self.select_3.setObjectName("select_3")
        self.degrees_buttonGroup.addButton(self.select_3)
        self.gridLayout_2.addWidget(self.select_3, 1, 2, 1, 1)
        self.select_D = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_D.setFont(font)
        self.select_D.setChecked(True)
        self.select_D.setObjectName("select_D")
        self.keys_buttonGroup.addButton(self.select_D)
        self.gridLayout_2.addWidget(self.select_D, 4, 0, 1, 1)
        self.select_Ab = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_Ab.setFont(font)
        self.select_Ab.setObjectName("select_Ab")
        self.keys_buttonGroup.addButton(self.select_Ab)
        self.gridLayout_2.addWidget(self.select_Ab, 4, 1, 1, 1)
        self.select_B = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_B.setFont(font)
        self.select_B.setObjectName("select_B")
        self.keys_buttonGroup.addButton(self.select_B)
        self.gridLayout_2.addWidget(self.select_B, 7, 1, 1, 1)
        self.select_4 = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.select_4.setFont(font)
        self.select_4.setChecked(True)
        self.select_4.setObjectName("select_4")
        self.degrees_buttonGroup.addButton(self.select_4)
        self.gridLayout_2.addWidget(self.select_4, 2, 2, 1, 1)
        ChordDegreeTestWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ChordDegreeTestWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1222, 18))
        self.menubar.setObjectName("menubar")
        ChordDegreeTestWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ChordDegreeTestWindow)
        self.statusbar.setObjectName("statusbar")
        ChordDegreeTestWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ChordDegreeTestWindow)
        QtCore.QMetaObject.connectSlotsByName(ChordDegreeTestWindow)

    def retranslateUi(self, ChordDegreeTestWindow):
        _translate = QtCore.QCoreApplication.translate
        ChordDegreeTestWindow.setWindowTitle(_translate("ChordDegreeTestWindow", "Chord Degree Test"))
        self.close_button.setText(_translate("ChordDegreeTestWindow", "Close"))
        self.label.setText(_translate("ChordDegreeTestWindow", "Select the note which is the indicated degree for the indicated key"))
        self.label_2.setText(_translate("ChordDegreeTestWindow", "Select the keys/degrees you would like to test"))
        self.degree_label.setText(_translate("ChordDegreeTestWindow", "Degree: "))
        self.skip_button.setText(_translate("ChordDegreeTestWindow", "Skip"))
        self.key_label.setText(_translate("ChordDegreeTestWindow", "Key: "))
        self.enharmonic_switch.setText(_translate("ChordDegreeTestWindow", "Turn on enharmonic equivalency"))
        self.G_button.setAccessibleName(_translate("ChordDegreeTestWindow", "G"))
        self.G_button.setText(_translate("ChordDegreeTestWindow", "G"))
        self.Fs_button.setAccessibleName(_translate("ChordDegreeTestWindow", "F#"))
        self.Fs_button.setText(_translate("ChordDegreeTestWindow", "F#"))
        self.Bs_button.setAccessibleName(_translate("ChordDegreeTestWindow", "B#"))
        self.Bs_button.setText(_translate("ChordDegreeTestWindow", "B#"))
        self.E_button_2.setAccessibleName(_translate("ChordDegreeTestWindow", "E"))
        self.E_button_2.setText(_translate("ChordDegreeTestWindow", "E"))
        self.A_button.setAccessibleName(_translate("ChordDegreeTestWindow", "A"))
        self.A_button.setText(_translate("ChordDegreeTestWindow", "A"))
        self.Gs_button.setAccessibleName(_translate("ChordDegreeTestWindow", "G#"))
        self.Gs_button.setText(_translate("ChordDegreeTestWindow", "G#"))
        self.Cs_button.setAccessibleName(_translate("ChordDegreeTestWindow", "C#"))
        self.Cs_button.setText(_translate("ChordDegreeTestWindow", "C#"))
        self.Gb_button.setAccessibleName(_translate("ChordDegreeTestWindow", "Gb"))
        self.Gb_button.setText(_translate("ChordDegreeTestWindow", "Gb"))
        self.Ds_button.setAccessibleName(_translate("ChordDegreeTestWindow", "D#"))
        self.Ds_button.setText(_translate("ChordDegreeTestWindow", "D#"))
        self.Eb_button.setAccessibleName(_translate("ChordDegreeTestWindow", "Eb"))
        self.Eb_button.setText(_translate("ChordDegreeTestWindow", "Eb"))
        self.B_button.setAccessibleName(_translate("ChordDegreeTestWindow", "B"))
        self.B_button.setText(_translate("ChordDegreeTestWindow", "B"))
        self.C_button.setAccessibleName(_translate("ChordDegreeTestWindow", "C"))
        self.C_button.setText(_translate("ChordDegreeTestWindow", "C"))
        self.Bb_button.setAccessibleName(_translate("ChordDegreeTestWindow", "Bb"))
        self.Bb_button.setText(_translate("ChordDegreeTestWindow", "Bb"))
        self.Ab_button.setAccessibleName(_translate("ChordDegreeTestWindow", "Ab"))
        self.Ab_button.setText(_translate("ChordDegreeTestWindow", "Ab"))
        self.Db_button.setAccessibleName(_translate("ChordDegreeTestWindow", "Db"))
        self.Db_button.setText(_translate("ChordDegreeTestWindow", "Db"))
        self.F_button.setAccessibleName(_translate("ChordDegreeTestWindow", "F"))
        self.F_button.setText(_translate("ChordDegreeTestWindow", "F"))
        self.Es_button.setAccessibleName(_translate("ChordDegreeTestWindow", "E#"))
        self.Es_button.setText(_translate("ChordDegreeTestWindow", "E#"))
        self.As_button.setAccessibleName(_translate("ChordDegreeTestWindow", "A#"))
        self.As_button.setText(_translate("ChordDegreeTestWindow", "A#"))
        self.D_button.setAccessibleName(_translate("ChordDegreeTestWindow", "D"))
        self.D_button.setText(_translate("ChordDegreeTestWindow", "D"))
        self.GsAb_button_3.setAccessibleName(_translate("ChordDegreeTestWindow", "G#/Ab"))
        self.GsAb_button_3.setText(_translate("ChordDegreeTestWindow", "G#/Ab"))
        self.B_button_5.setAccessibleName(_translate("ChordDegreeTestWindow", "B"))
        self.B_button_5.setText(_translate("ChordDegreeTestWindow", "B"))
        self.A_button_5.setAccessibleName(_translate("ChordDegreeTestWindow", "A"))
        self.A_button_5.setText(_translate("ChordDegreeTestWindow", "A"))
        self.AsBb_button_3.setAccessibleName(_translate("ChordDegreeTestWindow", "A#/Bb"))
        self.AsBb_button_3.setText(_translate("ChordDegreeTestWindow", "A#/Bb"))
        self.C_button_5.setAccessibleName(_translate("ChordDegreeTestWindow", "C"))
        self.C_button_5.setText(_translate("ChordDegreeTestWindow", "C"))
        self.CsDb_button_3.setAccessibleName(_translate("ChordDegreeTestWindow", "C#/Db"))
        self.CsDb_button_3.setText(_translate("ChordDegreeTestWindow", "C#/Db"))
        self.DsEb_button_3.setAccessibleName(_translate("ChordDegreeTestWindow", "D#/Eb"))
        self.DsEb_button_3.setText(_translate("ChordDegreeTestWindow", "D#/Eb"))
        self.F_button_5.setAccessibleName(_translate("ChordDegreeTestWindow", "F"))
        self.F_button_5.setText(_translate("ChordDegreeTestWindow", "F"))
        self.FsGb_button_3.setAccessibleName(_translate("ChordDegreeTestWindow", "F#/Gb"))
        self.FsGb_button_3.setText(_translate("ChordDegreeTestWindow", "F#/Gb"))
        self.G_button_5.setAccessibleName(_translate("ChordDegreeTestWindow", "G"))
        self.G_button_5.setText(_translate("ChordDegreeTestWindow", "G"))
        self.D_button_5.setAccessibleName(_translate("ChordDegreeTestWindow", "D"))
        self.D_button_5.setText(_translate("ChordDegreeTestWindow", "D"))
        self.E_button_5.setAccessibleName(_translate("ChordDegreeTestWindow", "E"))
        self.E_button_5.setText(_translate("ChordDegreeTestWindow", "E"))
        self.select_all_keys_button.setText(_translate("ChordDegreeTestWindow", "Select all keys"))
        self.select_all_degrees_button.setText(_translate("ChordDegreeTestWindow", "Select all degrees"))
        self.select_Eb.setAccessibleName(_translate("ChordDegreeTestWindow", "Eb"))
        self.select_Eb.setText(_translate("ChordDegreeTestWindow", "Eb"))
        self.select_5.setAccessibleName(_translate("ChordDegreeTestWindow", "5"))
        self.select_5.setText(_translate("ChordDegreeTestWindow", "5"))
        self.select_Bb.setAccessibleName(_translate("ChordDegreeTestWindow", "Bb"))
        self.select_Bb.setText(_translate("ChordDegreeTestWindow", "Bb"))
        self.select_Fs.setAccessibleName(_translate("ChordDegreeTestWindow", "F#"))
        self.select_Fs.setText(_translate("ChordDegreeTestWindow", "F#"))
        self.select_Db.setAccessibleName(_translate("ChordDegreeTestWindow", "Db"))
        self.select_Db.setText(_translate("ChordDegreeTestWindow", "Db"))
        self.select_F.setAccessibleName(_translate("ChordDegreeTestWindow", "F"))
        self.select_F.setText(_translate("ChordDegreeTestWindow", "F"))
        self.select_E.setAccessibleName(_translate("ChordDegreeTestWindow", "E"))
        self.select_E.setText(_translate("ChordDegreeTestWindow", "E"))
        self.select_7.setAccessibleName(_translate("ChordDegreeTestWindow", "7"))
        self.select_7.setText(_translate("ChordDegreeTestWindow", "7"))
        self.select_A.setAccessibleName(_translate("ChordDegreeTestWindow", "A"))
        self.select_A.setText(_translate("ChordDegreeTestWindow", "A"))
        self.select_G.setAccessibleName(_translate("ChordDegreeTestWindow", "G"))
        self.select_G.setText(_translate("ChordDegreeTestWindow", "G"))
        self.select_6.setAccessibleName(_translate("ChordDegreeTestWindow", "6"))
        self.select_6.setText(_translate("ChordDegreeTestWindow", "6"))
        self.select_Gb.setAccessibleName(_translate("ChordDegreeTestWindow", "Gb"))
        self.select_Gb.setText(_translate("ChordDegreeTestWindow", "Gb"))
        self.select_C.setAccessibleName(_translate("ChordDegreeTestWindow", "C"))
        self.select_C.setText(_translate("ChordDegreeTestWindow", "C"))
        self.select_Cs.setAccessibleName(_translate("ChordDegreeTestWindow", "C#"))
        self.select_Cs.setText(_translate("ChordDegreeTestWindow", "C#"))
        self.select_2.setAccessibleName(_translate("ChordDegreeTestWindow", "2"))
        self.select_2.setText(_translate("ChordDegreeTestWindow", "2"))
        self.select_3.setAccessibleName(_translate("ChordDegreeTestWindow", "3"))
        self.select_3.setText(_translate("ChordDegreeTestWindow", "3"))
        self.select_D.setAccessibleName(_translate("ChordDegreeTestWindow", "D"))
        self.select_D.setText(_translate("ChordDegreeTestWindow", "D"))
        self.select_Ab.setAccessibleName(_translate("ChordDegreeTestWindow", "Ab"))
        self.select_Ab.setText(_translate("ChordDegreeTestWindow", "Ab"))
        self.select_B.setAccessibleName(_translate("ChordDegreeTestWindow", "B"))
        self.select_B.setText(_translate("ChordDegreeTestWindow", "B"))
        self.select_4.setAccessibleName(_translate("ChordDegreeTestWindow", "4"))
        self.select_4.setText(_translate("ChordDegreeTestWindow", "4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ChordDegreeTestWindow = QtWidgets.QMainWindow()
    ui = Ui_ChordDegreeTestWindow()
    ui.setupUi(ChordDegreeTestWindow)
    ChordDegreeTestWindow.show()
    sys.exit(app.exec_())
